#%RAML 1.0 NamedExample
value:
 -
  firstname: Saurabh
  lastname: Jain
  address: Sadar bazar
  postal: 4770010
  country: India
  miles: 100
  nickname: jainy


 -
  firstname: Dharmendra
  lastname: Jain
  address: Sadar bazar
  postal: 477001
  country: India
  miles: 100
  nickname: jainy